### ISSUE TITLE
Metaheuristics.jl doesn't compile in Julia v1.11.0-alpha1

### ISSUE THREAD

**Issue by MichelJuillard** [jmejia8/Metaheuristics.jl#105]
Pre-compilation fails because `Base.compute_itscale` called at `./src/algorithms/SMS_EMOA/calc-hv.jl:6` doesn´t exist anymore in Julia v1.11.0-alpha1. See the discussion here: https://julialang.slack.com/archives/C67910KEH/p1709386724076639

**Comment by jmejia8** [comment]
Thank you for reporting.
