### ISSUE TITLE
Possible integration of MCCGA in Metaheuristics.jl

### ISSUE THREAD

**Issue by jbytecode** [jmejia8/Metaheuristics.jl#13]
Hi, 

Machine-coded Compact Genetic Algorithms (MCCGA for short) is an other single objective and real-valued optimizer introduced in 

- Satman, M. H. & Akadal, E. (2020). Machine Coded Compact Genetic Algorithms for Real Parameter Optimization Problems . Alphanumeric Journal , 8 (1) , 43-58 . DOI: 10.17093/alphanumeric.576919

and is implemented in 

https://github.com/jbytecode/MCCGA

as a non-standard Julia package and for testing purposes. The algorithm first estimates the probability of having 1 for each single bit  over the function domain (the term machine-coded comes from this stage). This vector of probabilities are then fed into a compact genetic algorithm. CGA directly works with the IEEE-758 bit representations of the real values. In the last step, a local optimizer is used for fine-tuning.  The performance of the algorithm can be easily explored using the package above. 

How about integrating this algorithm into the package Metaheuristics.jl ? Do you plan to expand the package content? Is this method suitable?  

I am open for any further collaborations. Thank you in advance!

**Comment by jmejia8** [comment]
Based on your response via DM, I started the implementation in [develop](https://github.com/jmejia8/Metaheuristics.jl/blob/71b571fd1015ca77e6ebe2c518d7f4527719050e/src/algorithms/MCCGA/MCCGA.jl) branch.

At this point, `MCCGA` is not working correctly in MHP due to I just copy, paste and adapt your code.

I have a question for you in the following line:

https://github.com/jmejia8/Metaheuristics.jl/blob/71b571fd1015ca77e6ebe2c518d7f4527719050e/src/algorithms/MCCGA/MCCGA.jl#L65

Thanks in advance.

**Comment by jbytecode** [comment]
sample(probvector) performs rand() call for each single bit, so in a p-variable problem it performs p x 32 x rand() calls in a map().

floats() is a little bit costy as it combines 32bits to build up an integer then later reinterpretes it as Float. 

imo, in initial state building, it is not the most costy part when it is compared to generating the initial probvector itself.

**Comment by jmejia8** [comment]
Thanks for your response. MCCGA is now implemented within the Metaheuristics.jl package (master branch).
It would be nice if the docstring about MCCGA is updated.

-  [This description is wrong](https://github.com/jmejia8/Metaheuristics.jl/blob/master/docs/src/algorithms.md#mccga) (my mistake).
- Bibliographic references can be inserted [here](https://github.com/jmejia8/Metaheuristics.jl/blob/master/docs/references.bib).
- The [docstring for this function](https://github.com/jmejia8/Metaheuristics.jl/blob/4d9d7882a5ba311c5b85d2d1f1db80648c21b071/src/algorithms/MCCGA/MCCGA.jl#L24) could be improved

## Example
```julia
using Metaheuristics

# MCCA requires Optim (unless you put MCCA(use_local_search=false))
import Optim 

# problem
f, bounds, solutions = Metaheuristics.TestProblems.rastrigin();

result = optimize(f, bounds, MCCGA())
```

Output:

```
+=========== RESULT ==========+
  iteration: 31419
    minimum: 0
  minimizer: [3.9383281247463824e-29, -1.60938227312533e-36, 5.963404220446944e-28, 6.760617690476724e-38, -1.3224051368625615e-32, 9.76955021280433e-39, -3.574582341995119e-38, 1.6852928556302238e-25, 1.776057958933574e-36, 4.273668128645299e-34]
    f calls: 63576
 total time: 3.3656 s
+============================+
```

**Comment by jbytecode** [comment]
that was super fast, thank you!

**Comment by jbytecode** [comment]
Just a quick and dirty PR, https://github.com/jmejia8/Metaheuristics.jl/pull/14, that adds the example below. I will enrich the documentation over time.

By the way, it seems MCCGA minimizes Rastrigin nicely :)
