### ISSUE TITLE
Add Decision-Making methods

### ISSUE THREAD

**Issue by jmejia8** [jmejia8/Metaheuristics.jl#17]
This new feature will include a posteriori decision-making.

Possible Usage Example:

```julia
julia> res = optimize(f, bounds, NSGA2())

julia> idx = decisionmaking(res, method) # or

julia> idx = decisionmaking(res.population, method) # or

julia> idx = decisionmaking(pareto_front(res), method) # or

julia> idx = method(res) # optional
```
`decision making` will return an integer vector containing solutions in `res.population` related to that decision suggested by the `method`. Possible alias for `decisionmaking`: `mcdm`.

Consider interfacing  https://github.com/jbytecode/JMcDM

**Comment by jbytecode** [comment]
nice, the mcdm functions follow a single pattern based on providing a dataframe, array of weights, and direction of optimizations. nice to see when integrated!

**Comment by jmejia8** [comment]
The integration will be easy thanks to the API implemented in JMcDM.

**Comment by jbytecode** [comment]
what are you planning for the weights? choosing them with equal chance by default? what is the preferred default method?

**Comment by jmejia8** [comment]
Nice question! I think weights have to be user-defined as well as `method`. However, after overthinking, I only will extend each core method in JMcDM (`mcdm`, `MCDMSetting`,  etc.), and let JMcDM handles those parameters.

Suggestions are welcome 🤓

**Comment by jbytecode** [comment]
a default method (maybe Topsis) with equal weights would be useful. It is not a subject which every researchers are supposed to have enough knowledge.

**Comment by jmejia8** [comment]
Now, JMcDM has an interface in Metaheuristics ([master branch](https://github.com/jmejia8/Metaheuristics.jl/tree/3ee0ee3022e1f0513976aad92950626d6cc296ec)). It can be noted that different nature DM methods have been implemented (many in JMcDM, a Region of Interest filter, and some Compromise Programming methods).

Note that JMcDM is loaded by [Requires.jl](https://github.com/JuliaPackaging/Requires.jl) and it is necessary to import it before Metaheuristics. Therefore, I was unable to establish a default method. Further releases will include an extended tutorial about using MCDM and Metaheuristics.

@jbytecode, it would be nice to know your opinion.

**Comment by jbytecode** [comment]
psi would be nice as it does not use weights.

do you want me to change mcdm() with default params?

**Comment by jmejia8** [comment]
> do you want me to change mcdm() with default params?

Yes, I do. Thanks for the support.

**Comment by jbytecode** [comment]
any contributions are welcome if possible, otherwise, I can implement a default behaviour.

**Comment by jmejia8** [comment]
Now, Metaheuristics.jl package  includes [Multi-Criteria Decision-Making](https://jmejia8.github.io/Metaheuristics.jl/dev/mcdm/#Multi-Criteria-Decision-Making) methods. An interface for https://github.com/jbytecode/JMcDM has been implemented covering the following functions and types: `mcdm`, `summary`, and `MCDMSetting`.

Moreover,  [CompromiseProgramming](https://jmejia8.github.io/Metaheuristics.jl/dev/mcdm/#Metaheuristics.CompromiseProgramming) and the  [ROIArchiving](https://jmejia8.github.io/Metaheuristics.jl/dev/mcdm/#Metaheuristics.ROIArchiving) methods have been also included.

The main functions to perform  MCDM are `decisionmaking` (alias `dm`) and `best_alternative`.

Example: https://jmejia8.github.io/Metaheuristics.jl/dev/examples/#Decision-Making
Documentation: https://jmejia8.github.io/Metaheuristics.jl/dev/mcdm/

Suggestions are welcome.

**Comment by jbytecode** [comment]
congrats! well done.
