### ISSUE TITLE
RAM issue when running large problems

### ISSUE THREAD

**Issue by scepeda78** [jmejia8/Metaheuristics.jl#2]
When using ECA, it starts to create the population, with a large problem with 30.000 parameters, and my RAM (128GB) is fully used, killing the process. Do you know a way to limit the ram usage?

Rgds

**Comment by jmejia8** [comment]
By default the population size in ECA is `N = K * D`  where `K = 7` and `D` is the dimension number (parameters), maybe you should change the value `N` (say `N=100`). Also limit the number of function evaluations.

Example:

```julia
options = Options(f_calls_limit=10_000)
method = ECA(N = 100, options = options)
optimize(f, bounds, method)
```

Note that ECA and the other metaheuristics implemented in this Package work well for up to 100 parameters. Probably later some methods for large-scale problems (>100 parameters) will be implemented.

**Comment by scepeda78** [comment]
Thanks now it worked!, I limited the population size.  Do you now if an initial population can be given as hot start solution?.

**Comment by jmejia8** [comment]
I already implemented that feature but is still at [develop branch](https://github.com/jmejia8/Metaheuristics.jl/blob/5f747aeff589824b68c1f9cfb40eb86838635e43/test/common-methods.jl#L106) 
It will be merged to main branch ASAP.

**Comment by scepeda78** [comment]
> I already implemented that feature but is still at [develop branch](https://github.com/jmejia8/Metaheuristics.jl/blob/5f747aeff589824b68c1f9cfb40eb86838635e43/test/common-methods.jl#L106)
> It will be merged to main branch ASAP.

How would you declare an starting point from the beginning?, since the example provided assume that you have a previous population and a result from a previous optimization process..

**Comment by jmejia8** [comment]
You can do it as follows:

```julia
f, bounds, optimums = Metaheuristics.TestProblems.get_problem(:sphere)
D = size(bounds,2)

# known solution
x_known = 0.6ones(D)

# random solutions (uniform distribution)
X = [ bounds[1,:] + rand(D).* bounds[2,:] for i in 1:19  ]

push!(X, x_known) # save an interest solution

# generate the population with 19+1 solutions
population = [ Metaheuristics.create_child(x, f(x)) for x in X ]

# prior state
prev_status = State(Metaheuristics.get_best(population), population)

# say to ECA that you have generated a population
method = ECA(N = length(population))
method.status = prev_status

# optimize
optimize(f, bounds, method)
```

If you also know `x_known` and `fx = f(x_known)`, then instead of pushing `x` into `X`,
you may do `push!(population,  Metaheuristics.create_child(x_known, fx))`.
