### ISSUE TITLE
Solving combinatorial problems using SA [DUPLICATED]

### ISSUE THREAD

**Issue by FeldrinH** [jmejia8/Metaheuristics.jl#25]
I have seen simulated annealing commonly used to optimize combinatorial problems such as TSP.
However, I can't seem to find a way to use SA as implemented in this package for combinatorial problems, since it seems to accept only a real-valued function and exposes no way to control how new solutions are generated.

Is it possible to use the SA implementation in this package for combinatorial problems and if so, then how?

**Comment by jmejia8** [comment]
Duplicated #26
