### ISSUE TITLE
Replacement of makeminmax() function in JMcDM

### ISSUE THREAD

**Issue by jbytecode** [jmejia8/Metaheuristics.jl#34]
In previous versions of JMcDM, the MCDM functions were taking a vector of `minimum()` and `maximum()` functions as arguments. Much of the MCDM methods were defined as 

`method(data, weight, fns::Vector{Function})`

however, this way of defining functions is not that convenient because in some cases, the type of 

`[minimum, minimum, minimum, ...]`

is not `Vector{Function}` but it is `Vector{typeof{minimum})` if all of the function names are the same.  This is why we recently implemented and used `makeminmax()` function. As of the v.0.5.6 MCDM functions are now defined like

```
function method(
    decisionMat::DataFrame,
    weights::Array{Float64,1},
    fns::Array{F,1},
)::MethodResult where {F<:Function}
```

so by now, there is no need for the `makeminmax()` function any more and it is replaced.

Fyi.

Note: https://github.com/jbytecode/JMcDM/commit/f5b460674e65b385a24d2ebcdc68765a7a941a81#diff-4c97c58141fa4df965438bbc167e0c5bc82e12c5e3e6dacb76f2cb2cd68ee682

**Comment by jmejia8** [comment]
Thank you for the information.

Noted it when my tests failed. I fixed it by restricting the JMcDM versions (https://github.com/jmejia8/Metaheuristics.jl/commit/a66a929e363e9aacc893bc8ec505467a24b4bd43). I hope the newer versions of JMcDM can be interfaced correctly.

**Comment by jbytecode** [comment]
@jmejia8 - thank you. now it is time to close this thread.
