### ISSUE TITLE
UnicodePlots Version

### ISSUE THREAD

**Issue by jbytecode** [jmejia8/Metaheuristics.jl#41]
There are newer versions of UnicodePlots (>= v3.0.0) and Metaheuristics.jl is not compatible with them. 

Is there a specific reason for this?

Thank you in advance.

**Comment by jbytecode** [comment]
https://github.com/jmejia8/Metaheuristics.jl/pull/42

**Comment by jmejia8** [comment]
Thank you for the PR.
