### ISSUE TITLE
Replacing Nelder-Mead with Hooke-Jeeves in MCCGA

### ISSUE THREAD

**Issue by jbytecode** [jmejia8/Metaheuristics.jl#43]
I am going to send a pull request that replaces Nelder-Mead local search part with Hooke-Jeeves in MCCGA algorithm.

This PR gains these items:

- Reduces the dependencies of outer packages
- Hooke-Jeeves is not only a local search algorithm but is a direct-search algorithm 
- Hooke-Jeeves does not use derivatives

**Comment by jmejia8** [comment]
What a great contribution! It would be nice to have Hooke-Jeeves (Pattern Search) as another implemented algorithm.

```julia
optimize(f, bounds, PatternSearch())
```

Since the Hooke-Jeeves method and other methods require a starting solution, I opened https://github.com/jmejia8/Metaheuristics.jl/issues/46 to solve those possible scenarios.

**Comment by jbytecode** [comment]
Yes, we can separate `hj()` from the `MCCGA` files and implement as an independent algorithm, of course in the next step.

**Comment by jmejia8** [comment]
I'm fine with that.

**Comment by jbytecode** [comment]
Since the PR is merged, we can close is this issue for now. 

When we get ready to implement Hooke & Jeeves as a separate algorithm, we can create a new one if needed.
