### ISSUE TITLE
Tests for multi-objectives fail

### ISSUE THREAD

**Issue by jbytecode** [jmejia8/Metaheuristics.jl#45]
After performing

```
(Metaheuristics) pkg>  test
```

I get

```julia
Multi objective: Test Failed at /Users/istar1/Desktop/code/julia/Metaheuristics.jl/test/multi-objective.jl:47
  Expression: Metaheuristics.PerformanceIndicators.igd(result.population, pf) <= 0.2
   Evaluated: 0.22673908824247319 <= 0.2
Stacktrace:
 [1] macro expansion
   @ ~/Julia/julia/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:477 [inlined]
 [2] (::var"#run_methods#20")(problem::Symbol)
   @ Main ~/Desktop/code/julia/Metaheuristics.jl/test/multi-objective.jl:47
```

Is 0.2267 reasonable or the right result? How about changing the threshold or using a RNG to generate an exact solution in each time?

Thanks.

**Comment by jmejia8** [comment]
Using a RNG is the best option (suggested by https://github.com/jmejia8/Metaheuristics.jl/issues/24); however, a lot of work is required due to we need to update every `rand(...)` by `rand(rng, ...)`.

Changing the threshold (say 0.5) is OK for me.

**Comment by jbytecode** [comment]
I am going to send a PR for this.

**Comment by jbytecode** [comment]
I think this PR solves it and I have all of the tests passed in my machine.

**Comment by jbytecode** [comment]
Solved.
