### ISSUE TITLE
How to pass a pre-calculated distance matrix to the function f(x)?

### ISSUE THREAD

**Issue by jrklasen** [jmejia8/Metaheuristics.jl#58]
Hi there, 
thanks for the work on this great package. I have a question rather than an actual problem with the package. 
I couldn't figure out how to pass a pre-calculated distance matrix to the function f(x), could someone give me a hint on that matter?

**Comment by jmejia8** [comment]
Hi! Bellow some examples:

```julia
M = rand(10,10) # your matrix
f(x) = M*x
optimize(f,  bounds)
```
or

```julia
function obj_func(x, M)
    # . . .
    M*x
end

M = rand(10,10) # your matrix
optimize(x ->  obj_func(x, M), bounds)
```

**Comment by jrklasen** [comment]
Ah great, thank you! Now, where I see it, it seems so obvious.
