### ISSUE TITLE
How to display the best fintess for each iteration

### ISSUE THREAD

**Issue by licheng0794** [jmejia8/Metaheuristics.jl#60]
For any optimization algorithms, we expect to show the fitness value for each iteration. How could we do that for Metaheuristics.jl? I tried to find in Options but I cannot find it. Thank you.

**Comment by jmejia8** [comment]
Use `debug` in [`Options`](https://jmejia8.github.io/Metaheuristics.jl/stable/api/#Metaheuristics.Options),

For custom formats, I suggest using the following:
```julia
logger(status) = println(status.iteration," ", minimum(status))

optimize(f, bounds, OPTIMIZER; logger = logger)
```

See also [`State`](https://jmejia8.github.io/Metaheuristics.jl/stable/api/#Metaheuristics.State).

**Comment by licheng0794** [comment]
I tested debug in Options using the example from the API documents. It does work well. 

However, I tested it for my own function, which includes an ODE solver. It did not work. Not sure what the problem is. The code is below.

function fitness_multiobj(X)

    X = [round(x,digits=5) for x in X]

    println(X)

    outV = VHRSteady(X)

    abs(outV[1] - targetoutflow[2]) + abs(outV[2] - targetoutflow[3]) + 10*abs(outV[3] - targetoutflow[4]) + abs(outV[5] - targetoutflow[5])
end

**Comment by licheng0794** [comment]
I found the reason. The debug information is only shown after one interation not one evaluation. Thank you.

**Comment by jmejia8** [comment]
Nice!
