### ISSUE TITLE
Fast time-to-first call methods using SnoopPrecompile

### ISSUE THREAD

**Issue by jbytecode** [jmejia8/Metaheuristics.jl#71]
Hi,

Do you have any plans to integrate the package with SnoopPrecompile?

It drastically reduces the time-to-first call methods.

Here is what I did for LinRegOutliers: https://github.com/jbytecode/LinRegOutliers/blob/master/src/precompile/precompile.jl

Best.

**Comment by jmejia8** [comment]
What a nice recommendation! SnoopPrecompile could be integrated in the future.

This thread can be used to add a list of methods requiring this kind of performance improvement.

Thank you!

**Comment by jbytecode** [comment]
Its integration is quite easy. Ping me if you need any help! Thank you.

**Comment by jmejia8** [comment]
Please, feel free to send PRs on this regard. Your contributions are always welcome.

**Comment by jbytecode** [comment]
of course, I'll try to implement a skeleton in a few days.

**Comment by jbytecode** [comment]
Here is the first PR: https://github.com/jmejia8/Metaheuristics.jl/pull/72

**Comment by jbytecode** [comment]
sure, thank you
