### ISSUE TITLE
Reuse intervals from IntervalSets.jl

### ISSUE THREAD

**Issue by aplavin** [jmejia8/Metaheuristics.jl#82]
Starting from a recent version of Metaheuristics, it defines and exports `..`. This binding clashes with intervals packages, with `IntervalSets.jl` being the most popular one by far.
Aside from the usage inconvenience coming from the clash, relying on well-tested and reliable intervals machinery from `IntervalSets` would also be nice.

So, please consider reusing already existing intervals from the `IntervalSets.jl` package, instead of defining another interval type.

**Comment by jmejia8** [comment]
Thank you for letting me know. Actually, [SearchSpaces](https://github.com/jmejia8/SearchSpaces.jl)  is exporting `..` and Metaheuristics re-exporting it. Therefore, the issue will be solved there :)
