### ISSUE TITLE
xfgh_solution vs xFgh_solution vs xf_solution

### ISSUE THREAD

**Issue by jbiffl** [jmejia8/Metaheuristics.jl#88]
I keep running into method errors like this one 
```julia
no method matching compare(::Metaheuristics.xfgh_solution{Vector{Float64}}, ::Metaheuristics.xfgh_solution{Vector{Float64}})
```
and I am having trouble figuring out what the differences between xfgh_solution and xFgh_solution and xf_solution are and how each type is generated/what it means. I was unable to find anything in documentation about this internal type system, and I'm not sure why `Metaheuristics.is_better()` has dispatches for `xf_solution`, `xfgh_solution`, and `xFgh_solution` types, but `Metaheuristics.compare()` only has a dispatch for `xFgh_solution` which does not work with `xfgh_solution`. 

Any information you can provide on the differences between these seemingly similar types would be very helpful.

Thanks!

**Comment by jmejia8** [comment]
Hi!

- `is_better(a, b)` returns a boolean indicating whether solution `a` is better than `b` (minimum objective function value).
- [`compare(a, b)`](https://jmejia8.github.io/Metaheuristics.jl/stable/api/#Metaheuristics.compare) has been designed for multi-objective problems to compare solutions in objective space (using [Pareto dominance](http://home.uchicago.edu/bdm/pepp/pareto.pdf)). This method returns an integer.

Struct `xf_solution` is to save decision $x$ and function values $f(x)$ of single-objective unconstrained problems, `xfgh_solution` for single-objective and constrained. Finally, `xFgh_solution` for multi-objective problems.

**Comment by jbiffl** [comment]
Thanks a lot for the answer! That makes sense now.

Are multi-objective algorithms are only compatible with multi-objective problems then? E.g. for an objective function which has a programmatically generated set of objectives I would need to use a different algorithm for cases where there is only a single objective than when there are multiple objectives.

**Comment by jmejia8** [comment]
MO algorithms work better for MO problems. They can also solve single-objective problems with a proper definition of an objective function (convert the number `fx` into a vector `[fx]`). Of course, the selection of an optimization algorithm is depending on the optimization problem.

**Comment by jbiffl** [comment]
Thank you for clarifying, that seems reasonable.
