### ISSUE TITLE
Handle unstable objective function output

### ISSUE THREAD

**Issue by jmejia8** [jmejia8/Metaheuristics.jl#89]
Improve error reporting for cases like:

```julia
julia> f(x) = rand(rand(1:3)), [0.0], [0.0]
f (generic function with 1 method)

julia> optimize(f, [-1 -1 -1;1 1 1.0])

```

**Comment by AlexanderNenninger** [comment]
This question is also relevant for noisy functions? Are there any heuristics that can deal with them?

**Comment by jmejia8** [comment]
No, only for cases when the user defines an objective function which returns arrays of different sizes.
At the current time, implemented heuristics can solve deterministic functions. However, they can return a candidate solution.
