### ISSUE TITLE
Typo in `update_state!` for DE.jl

### ISSUE THREAD

**Issue by jonathanfischer97** [jmejia8/Metaheuristics.jl#98]
In the file DE.jl, there is a reference to F_max on line 96 which is not defined in the scope of `update_state!` and throws an error when `DE` is constructed with an `F_max` value. Here is the typo:

## Typo
```
if parameters.F_min < parameters.F_max
    F = parameters.F_min + (F_max - parameters.F_min) * rand(rng)
end
```

## Solution
```
if parameters.F_min < parameters.F_max
    F = parameters.F_min + (parameters.F_max - parameters.F_min) * rand(rng)
end
```

**Comment by mcamilletti1** [comment]
Submitted a PR to fix this!

**Comment by jmejia8** [comment]
Thank you! 

https://github.com/jmejia8/Metaheuristics.jl/pull/101

Merged.
